### ISSUE TITLE
Not sure how to use -   multiClient.auth and   multiClient.select for Mongodb database

### ISSUE THREAD

**Issue by anil826** [sagiegurari/multiple-redis#6]
I want to use this plug as Redis backup with my existing application but it looks like it is not supporting the  `select` and `auth` methods. 

So when standard `redis` server goes down then I want to run/use the another (backup) server. 

**Error Stack**
```console
MULTIPLE-REDIS 12720: Redis command: auth, args: iOw4gTQ5yWX5DJeH, output:  OK
MULTIPLE-REDIS 12721: Error while redis command: auth, args: iOw4gTQ5yWX5DJeH,  ReplyError: ERR invalid password
    at new Command (/user/Documents/qform_builder/node_modules/multiple-redis/node_modules/redis/lib/command.js:12:22)
    at RedisClient.auth (/user/Documents/qform_builder/node_modules/multiple-redis/node_modules/redis/lib/individualCommands.js:210:42)
    at RedisClient.send_command.RedisClient.sendCommand (/user/Documents/qform_builder/node_modules/multiple-redis/node_modules/redis/lib/extendedApi.js:46:26)
    at MultiRedisClient.invokeCommandOnClient (/user/Documents/qform_builder/node_modules/multiple-redis/lib/multiple-redis.js:361:16)

```

**Code Sample**
```js
//Standard Redis server
//Standard redis server
  var multiClient = MultipleRedis.createClient([
    {
      port: config.port,
      host: config.host
    },
    {
      port: backup_config.port,
      host: backup_config.host
    },
  ]);
  if (config.auth) {
      var auth = (config.auth.indexOf(":") > 0) ? config.auth.split(":")[1] : config.auth;
      multiClient.auth(auth);
    }
    if (config.db) multiClient.select(config.db);
    app.redis = multiClient;
  multiClient.on("ready", function() {
    console.log("Redis connected to: redis://"+config.host+":"+config.port);
  });

  multiClient.on("error", function() {
    console.log("Error: Redis could not connect to: redis://"+config.host+":"+config.port);
  });

```

**Comment by sagiegurari** [comment]
auth should work just fine,but the error is invalid password so doesn't seem related to multi redis.
never used select before but not sure if its an issue to submit but inmulti redis env could be a problem logically

**Comment by anil826** [comment]
Thanks for quick reply @sagiegurari  , 
I am basically storing the client/user session on Redis-server and without `multiClient` it is working fine for me not sure if we have any alternative of `select` command.

**Comment by anil826** [comment]
This is the debug log which I am getting 

```
Redis connection is gone from end event.
Redis connection is gone from end event.
Redis connection is gone from end event.
Redis connection is gone from end event.
Retry connection in 200 ms
Retry connection in 200 ms
Retry connection in 200 ms
Retry connection in 200 ms
Retrying connection...
Retrying connection...
Retrying connection...
Retrying connection...
Sending auth to hammerjaw.redistogo.com:xxx id 1
Send hammerjaw.redistogo.com:xxxxx id 1: *2
$4
auth
$16
iOw4gTQWERW

Sending auth to hammerjaw.redistogo.com:xxx id 1
Send hammerjaw.redistogo.com:xxxx id 1: *2
$4
auth
$16
iOw4gTQWERW

Sending auth to hammerjaw.redistogo.com:xxxx id 1
Send hammerjaw.redistogo.com:xxxx id 1: *2
$4
auth
$16
iOw4gTQWERW

Sending auth to hammerjaw.redistogo.com:xxxx id 1
Send hammerjaw.redistogo.com:xxxxx id 1: *2
$4
auth
$16
iOw4gTQWERW

Stream connected hammerjaw.redistogo.com:xxxxx id 1
Stream connected hammerjaw.redistogo.com:xxxx id 1
Stream connected hammerjaw.redistogo.com:xxxx id 1
Stream connected hammerjaw.redistogo.com:xxxx id 1
Checking server ready state...
Checking server ready state...
Checking server ready state...
Checking server ready state...
Send hammerjaw.redistogo.com:xxxx id 1: *1
$4
info

Send hammerjaw.redistogo.com:xxxx id 1: *1
$4
info

Send hammerjaw.redistogo.com:xxx id 1: *1
$4
info

Send hammerjaw.redistogo.com:xxxx id 1: *1
$4
info

Net read hammerjaw.redistogo.com:xxx id 1
Net read hammerjaw.redistogo.com:xxx id 1
Net read hammerjaw.redistogo.com:xxx id 1
Error: Redis could not connect to: redis://redis-xxx.c15.us-xx-1-4.xx.cloud.redislabs.com:xxxx

```

**Comment by sagiegurari** [comment]
wait. trying to figure out, the auth works ok?
is the issue only with 'select'?

**Comment by anil826** [comment]
@sagiegurari , Not sure I comment both but still getting the same error.

**Comment by anil826** [comment]
> wait. trying to figure out, the auth works ok? Not sure
> is the issue only with 'select'? Yes 

I am using Heroku Redis add-on I think this should be fine ..

**Comment by sagiegurari** [comment]
you don't need anything special in the options...
https://github.com/sagiegurari/multiple-redis/blob/master/docs/api.md#MultiRedisClient.createClient

This is used in production with auth so i know that one works.
i never used select before. from reading about it, in cluster mode (multi redis is not cluster mode, but it is similar in a way), this command should not be used. but... i didn't dig too deep regarding it.

**Comment by anil826** [comment]
Hey @sagiegurari ,
I think the simple example which you mention in the doc is not working for me not sure if I am doing anything wrong. 

```
if (redis_url && redis_backup_url) {
    try {
      var redis_connection = url.parse(redis_url);
      //Backup redis server url
      var backup_redis_connection = url.parse(redis_backup_url);
      config = {
        host: redis_connection.hostname,
        port: redis_connection.port,
        auth: redis_connection.auth
      };
      //Backup configuration
      backup_config = {
        host: backup_redis_connection.hostname,
        port: backup_redis_connection.port,
        auth: backup_redis_connection.auth
      }
    }
    catch(e) {
      // error pulling redis_togo params
      console.log('Error pulling redis_togo params from ENV', redis_url, e);
    }
  }

  redis.debug_mode = config.debug
  //Standard redis server
  var client1 = redis.createClient(config);
  //backup_client redis server
  var client2 = redis.createClient(backup_config);
  //
  var multiClient = MultipleRedis.createClient([client1, client2]);

  multiClient.once('all-ready', function onReady() {
    //run any command on the multi client instead of the original clients
    console.log('Multi-redis is connected .. !!!!')
    
  });
```
**I am getting the error on this event -** 
 ```
multiClient.on("error", function() {
    console.log("Error: Redis could not connect to: redis://"+config.host+":"+config.port);
  });
```

**Comment by sagiegurari** [comment]
whats the error? you are not using the error object on the onError event handler

**Comment by anil826** [comment]
> whats the error? you are not using the error object on the onError event handler

I am using the `on error` event and on this event, I am getting the console logs - 
`Error: Redis could not connect to: redis://` 
` multiClient.once('all-ready',` never going to executed.

**Comment by sagiegurari** [comment]
can you take the error obj from the event and print itm

**Comment by anil826** [comment]
> can you take the error obj from the event and print it?

**Error**

`Error: Ready check failed: NOAUTH Authentication required. at RedisClient.on_info_cmd`

**Comment by sagiegurari** [comment]
i'm not familiar with 'auth'. didn't you mean auth_pass?

**Comment by anil826** [comment]
> i'm not familiar with 'auth'. didn't you mean auth_pass?

I do pass the auth this is the token `args: iOw4gTQ5`

**Comment by sagiegurari** [comment]
no, i mean the property auth. it is supposed to be auto_pass.

**Comment by sagiegurari** [comment]
see https://github.com/NodeRedis/node_redis#options-object-properties

**Comment by anil826** [comment]
> no, i mean the property auth. it is supposed to be auth_pass.
I try and get this error. 
` multiClient.auth_pass is not a function`

**Comment by sagiegurari** [comment]
in your code instead of
```js
config = {
        host: redis_connection.hostname,
        port: redis_connection.port,
        auth: redis_connection.auth //this is a bug
      };
```

do
```js
config = {
        host: redis_connection.hostname,
        port: redis_connection.port,
        auth_pass: redis_connection.auth
      };
```

**Comment by anil826** [comment]
> see https://github.com/NodeRedis/node_redis#options-object-properties

It should be `auth` only
https://github.com/NodeRedis/node_redis#clientauthpassword-callback

**Comment by sagiegurari** [comment]
don't confuse auth operation and auth_pass property

**Comment by anil826** [comment]
> don't confuse auth operation and auth_pass property

I try both with `multi-redis` getting the same error with `redis` only normla `auth` is working fine

**Comment by sagiegurari** [comment]
you created the redis client manually, outside multi redis.
so if auth fails, its not related to multi redis.
i'm not sure what code you are running as i'm getting bits and pieces.
create a gist with full example of your code and i'll check it.

**Comment by anil826** [comment]
> you created the redis client manually, outside multi redis.
> so if auth fails, its not related to multi redis.
> i'm not sure what code you are running as i'm getting bits and pieces.
> create a gist with full example of your code and i'll check it.

https://gist.github.com/anil826/82a9941575b9f5b519265a6a2030f502

**Comment by sagiegurari** [comment]
i'm sorry but your code is a mess.
i cleaned it up and it works good.

here you create 2 redis clients and provide them to multi redis
```js

  //Standard redis server
  var client = redis.createClient(config.port, config.host);
  if (config.auth) {
    var auth = (config.auth.indexOf(":") > 0) ? config.auth.split(":")[1] : config.auth;
    client.auth(
  var client1 = redis.createClient(config);
  //backup_client redis server
  var client2 = redis.createClient(backup_config);
  //
  var multiClient = MultipleRedis.createClient([client1, client2]);
```

but then you create ANOTHER redis client and do auth for that one
```js
  var client = redis.createClient(config.port, config.host);
  if (config.auth) {
    var auth = (config.auth.indexOf(":") > 0) ? config.auth.split(":")[1] : config.auth;
    client.auth(
  var client = redis.createClient(config.port, config.host);
  if (config.auth) {
    var auth = (config.auth.indexOf(":") > 0) ? config.auth.split(":")[1] : config.auth;
    client.auth(
```

my test, i did the following
1. ran to local redis servers with password mypassword (i'm using redis 4.0.6 which might be old)
2. created 2 redis clients like you
3. create multi redis like you
4. got the all ready event.

```js
var redis = require('redis'),
    url = require('url');
//create the wrapper client
var MultipleRedis = require('multiple-redis');

//Standard redis server
var client1 = redis.createClient({
    host: 'localhost',//redis_connection.hostname,
    port: 6379,//redis_connection.port,
    auth_pass: 'mypassword'//redis_connection.auth
  });
//backup_client redis server
var client2 = redis.createClient({
    host: 'localhost',//backup_redis_connection.hostname,
    port: 6380,//backup_redis_connection.port,
    auth_pass: 'mypassword'//backup_redis_connection.auth
  });
//
var multiClient = MultipleRedis.createClient([client1, client2]);

multiClient.once('all-ready', function onReady() {
//run any command on the multi client instead of the original clients
console.log('Multi-redis is connected .. !!!!')

});

multiClient.once('error', function onReady(err) {
//run any command on the multi client instead of the original clients
console.log('Errrrr .. !!!!')
console.log(err)

});
```

**Comment by anil826** [comment]
> dis client and d

Thanks, I share wrong code my bad I will re-check

**Comment by anil826** [comment]
You are right the error is not related to multi-Redis I guess there are some setup for culter in my node application which is causing the issue.

```
var cluster = require('cluster');
var os = require('os');

module.exports = function balance(init, max) {
  return cluster.isMaster? initMaster() : init();
};

function initMaster() {

  cluster.on('disconnect', function(worker) {
    console.error('Cluster worker disconnect! Forking new worker.');
    cluster.fork();
  });

  var workerCount = process.argv[3] || os.cpus().length;
  var i = workerCount;
  while(i--) {
    cluster.fork();
  }
}
```

**Comment by anil826** [comment]
I found the issue I guess after authenticate both it is working fine.

```
if (config.auth_pass) {
    client1.auth(config.auth_pass);
  }
  
  if (backup_config.auth_pass) {
    client2.auth(backup_config.auth_pass);
  }
```

**Comment by anil826** [comment]
Thank you very much for helping me. :)
